services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - app_net

  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: payment
      POSTGRES_USER: payment
      POSTGRES_PASSWORD: payment
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app_net

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-app
    depends_on:
      - postgres
      - rabbitmq
    environment:
      SERVER_PORT: 3000
      RABBIT_CONNECTION_STRING: amqp://guest:guest@rabbitmq:5672
      DATABASE_URL: postgresql://payment:payment@postgres:5432/payment?schema=main
    ports:
      - "3000:3000"
    networks:
      - app_net

networks:
  app_net:
    driver: bridge

volumes:
  pgdata:
